# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa2016a62d333e6a52f5fe963f54ed0a928af2d61440627858933da5ccefc7e23cd8fd407ee42eef0478d47f223025edd9200004e96cf1a82111db15d2995be6

test:
  secret_key_base: 7aaa3b09e0dcc4c5d7e307b9f483575787cacf05311921171d3e6e1c66d132b8f5a6e2d888a0ce5e528608892d6407011eab9126a83edb37f6334e024752af73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
